#!/bin/bash

ABSPATH=$(cd "$(dirname "$0")"; pwd)
echo ""
echo ""
echo "-=== ALL PARAMS ===-"
echo $@
echo ""
echo ""
echo "-=== FILTERED PARAMS ===-"
FILTEREDPARAMS=`$ABSPATH/filterargs $@`
FNAME=`$ABSPATH/filtername $@ | tr -d ' '`

FNAME=`pwd`/$FNAME

ABSPATH=$(echo $ABSPATH | sed s/scratch/local/g)

FILTEREDPARAMS=$(echo $FILTEREDPARAMS | sed s/scratch/local/g)
FNAME=$(echo $FNAME | sed s/scratch/local/g)

echo $FILTEREDPARAMS
echo filename "$FNAME"

echo ""
echo ""
/usr/bin/gcc $@

# set output files
outBase="$(dirname $FNAME)/$(basename $FNAME .c)"
outDbg="$outBase.dbg"
outPartialPreproc="$outBase.pi"
outErr="$outBase.err"
outTime="$outBase.time"

# base parameters
baseParam="
	--bdd --no-warnings \
	-I /usr/local/include \
	-I /usr/lib/gcc/x86_64-linux-gnu/4.7/include-fixed \
	-I /usr/lib/gcc/x86_64-linux-gnu/4.7/include \
	-I /usr/include/x86_64-linux-gnu \
	-I /usr/include 
	--platfromHeader    $ABSPATH/platform.h \
	--openFeat          $ABSPATH/openfeatures.txt \
	--featureModelDimacs $ABSPATH/OpenSSL.dimacs \
	--include $ABSPATH/partial_configuration.h \
	--reuseAST \
	--recordTiming --parserstatistics --lexNoStdout \
	$FILTEREDPARAMS "

# run typechef only in case we have a c file
if [[ -f $FNAME ]];
then

	echo "Starting TypeChef"
	sbatch -p chimaira  -A spl -n 1 -c 2 --time=06:00:00  --mem_bind=local --output=/dev/null --error=/dev/null  /home/janker/clusterScripts/ossl_sampling.sh $FNAME $baseParam

	# TypeChef resides next to TypeChef-<projectname> two levels up
	# create the serialized AST in the first run
	# apply sampling and family-based analysis for each strategy afterwards
	# in a single run
fi

echo "Finished"
echo ""
